- src/komodo.h
- src/komodo_bitcoind.h
- src/komodo_notary.h
- src/main.cpp
- src/main.h
- src/miner.cpp
- zcutil/build.sh
DO NOT MINE with this branch. I repeat, do not use this branch for mining.
> Testmaster2

- doc/beefy-node-reference-komodo.conf
...to link within README.md to provide a solution for people looking to run a beefy full node **without** mining.
> A reference komodo.conf for a Xeon class node

- src/komodo_bitcoind.h
- src/komodo_gateway.h
- src/miner.cpp
- src/pow.cpp
interest change activation
AC output check
> merge master

- .gitlab-ci.yml
- makeRelease.sh
Adding GitLab CI configuration for komodo builds
Modifying makeRelease.sh to add additional dynamic libraries to the mac artifact package to support MacOS Sierra systems.
> GitLab-CI integration

- depends/packages/zeromq.mk
- src/Makefile.am
- src/cc/CCtokens.cpp
- src/cc/cclib.cpp
- src/cc/rogue/cursesd.c
- src/cc/rogue/init.c
- src/cc/rogue/main.c
- src/cc/rogue/mdport.c
- src/cc/rogue/rogue.c
- src/cc/rogue/rogue.h
- src/cc/rogue/rogue_player.h
- src/cc/rogue/save.c
- src/cc/rogue/state.c
- src/cc/rogue_rpc.cpp
sync jl777:jl777 -> komodoplatform:rogue_multiOS
> sync jl777

- qa/rpc-tests/test_framework/util.py
- src/init.cpp
- src/main.cpp
- src/rpc/blockchain.cpp
- src/txmempool.cpp
- src/txmempool.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/zcash/Note.cpp
@tonymorony please test
@DeckerSU please review and approve
> fix PING/REJECT attack [CVE-2019-17048, CVE-2019-16930]

- src/komodo_gateway.h
> check notaryproofvintx

- depends/packages/libsodium.mk
prevents script fetch from savannah.gnu.org
Contributor: @DeckerSU
> dont update libsodium config scripts

- src/assetchains.old
Because ease of use and utility seems better than pseudo-chronology.
> Update assetchains.old sort oder

- .github/workflows/komodod_ci.yml
> Remove dead MSFT dependency

- qa/pytest_komodo/basic/test_rawtransactions.py
Prevents false fails like:
https://github.com/KomodoPlatform/komodo/pull/298/checks?check_run_id=497945361
> fix rawtransactions tests amount

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yaml
- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
- qa/pytest_komodo/basic/pytest_util.py
- qa/pytest_komodo/basic/test_rawtransactions.py
- qa/pytest_komodo/basic/test_shielded.py
- qa/pytest_komodo/basic/test_wallet.py
- qa/pytest_komodo/cc_modules/test_channels.py
- qa/pytest_komodo/cc_modules/test_dice.py
- qa/pytest_komodo/cc_modules/test_faucet.py
- qa/pytest_komodo/cc_modules/test_heir.py
- qa/pytest_komodo/cc_modules/test_oracles.py
- qa/pytest_komodo/cc_modules/test_rewards.py
- qa/pytest_komodo/cc_modules/test_token.py
- qa/pytest_komodo/cc_modules/util.py
- qa/pytest_komodo/chainconfig.json
- qa/pytest_komodo/chainstart.py
- qa/pytest_komodo/ci_set_dex.sh
- qa/pytest_komodo/ci_sync_chain.sh
- qa/pytest_komodo/conftest.py
- qa/pytest_komodo/modules/test_dexp2p.py
- qa/pytest_komodo/modules/test_dexp2p_e2e.py
- qa/pytest_komodo/start_set_dex.bat
- qa/pytest_komodo/start_sync_ci.bat
- qa/pytest_komodo/sync/pytest_util.py
- qa/pytest_komodo/sync/test_sync.py
- zcutil/build-mac-dtest.sh
- zcutil/build-win-dtest.sh
Updated CC tests (switched to decimal only, updated some tests logic)
Enabled Win and Mac tests
Separate CI workflows for each OS
Triggers only on PR
Enabled DEXp2p tests in workflows
> Updated CC tests and CI workflows for research branch

- depends/packages/openssl.mk
upgrading openssl 1.1.1a -> 1.1.1f
> upgrade openssl

- .gitignore
Just to fix my `git add src` workflow :slightly_smiling_face:
> Add some entries to .gitignore

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
GH CI build/tests triggering once a week to prevent dead deps issue
> run CI workflows every Monday

- .github/workflows/komodo_linux_ci.yml
> remove mysql-server from gha worker

- src/cryptoconditions/src/cryptoconditions.c
- src/cryptoconditions/src/internal.h
- src/cryptoconditions/tests/test_failure_modes.py
Fix an issue where fingerprints with many members were not getting encoded correctly
> fix fingerprint encoding

- src/rpc/misc.cpp
> bump version - major update

- src/ac/k64
- src/ac/ksb
- src/ac/our
- src/ac/zexo
- src/assetchains.json
- src/assetchains.old
- src/fiat/k64
- src/fiat/ksb
- src/fiat/our
- src/fiat/sec
- src/fiat/zexo
Removed the "inactive" coins according to https://github.com/KomodoPlatform/dPoW/commit/89901aaeb7b42baef5e448755712b67e812beda2
&
https://github.com/KomodoPlatform/dPoW/commit/43224ad1d5b124ca08fd8194050ff208ce1a38b0
Also added missing `$1` in some coin start param in `assetchains.old` file. This helps passing additional arg when launching the script.
Please review. Thanks.
> remove "inactive" coins

- src/komodo_DEX.h
Detailed description of issue can be found in this post:
https://discord.com/channels/412898016371015680/458865442056830977/757945218766209065
> fix incorrect recvaddr output in DEX_stats RPC

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
- zcutil/build-mac-dtest.sh
- zcutil/build-mac.sh
Small fixes corresponding to github workers changes.
> Workflow CI fixes

- qa/pytest_komodo/basic/pytest_util.py
- qa/pytest_komodo/cc_modules/test_heir.py
> tmp disable heirCC check

- src/assetchains.json
- src/assetchains.old
aligning with active dpow coins in https://github.com/KomodoPlatform/dPoW/blob/dev/README.md
> Update assetchains.json & assetchains.old 

- src/miner.cpp
- fix issue described in https://github.com/KomodoPlatform/komodo/issues/398
- refactor scriptPubkey creation from reservekey
> fix daemon crash issue on getblocktemplate with -disablewallet arg

- src/miner.cpp
- src/pubkey.h
Running static analysis tool `cppcheck` found a few small things to fix in the src directory.
> Minor fixes from cppcheck

- src/cc/CCtokens_impl.h
- src/cc/CCutils.cpp
- src/cryptoconditions/src/internal.h
- src/cryptoconditions/src/secp256k1.c
- src/cryptoconditions/src/threshold.c
- src/rpc/tokensrpc.cpp
- src/tui/tui_assets_orders.py
- zcutil/build-mac.sh
fixes to tokentransfer MofN change;
fix for partial fulfulmment ser in lib cryptoconditions
test cases for tokentransfer MofN
> Updates to komodoplatform research 

- qa/pytest_komodo/cc_modules/test_token.py
- src/cc/CCassetstx_impl.h
- src/cc/import.cpp
- src/test-komodo-cc/test-assets.cpp
- src/test-komodo/test_addrman.cpp
- src/tui/tui_assets_orders.py
set correct ownerpk in tokencancelask/bid
do not add totally filled orders to tokenorders list
> Tokel order expiration fix: set correct owner pk in tokencancelask/bid

- README.md
This readme will be different to the normal Komodo readme's as it will host Tokel specific information and links.
> Update the tokel branch README

- src/checkqueue.h
- src/main.cpp
https://github.com/bitcoin/bitcoin/pull/9497
> Fix CCheckQueue IsIdle (potential) race condition

- depends/packages/boost.mk
- depends/patches/boost/fix-Solaris.patch
https://github.com/boostorg/thread/commit/74fb0a26099bc51d717f5f154b37231ce7df3e98
> fix boost build with glibc 2.34 on Linux platforms

- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
- Dockerfile.release
@SirSevenG there are some failing tests on CCs and with windows, can you please have a look?
> use py3, ubuntu 20, allow brew update errors to continue

- src/main.cpp
- src/miner.cpp
- src/net.cpp
- src/net.h
- src/rpc/net.cpp
- src/test-komodo/testutils.cpp
- src/validationinterface.cpp
- src/validationinterface.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- 1d933a8f7 Add logging and addr rate limiting statistics
- 152e1f942 Randomize the order of addr processing
- 2bec27973 Rate limit the processing of incoming addr messages
- 41b689185 Remove mapRequest tracking that just effects Qt display.
> Back-merge hotfixes to dev

- src/komodo_utils.cpp
Better solution for the issues mentioned in https://github.com/KomodoPlatform/komodo/pull/589 .
> allow -ac_private for the ZOMBIE test chain

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
Artifact actions v3 will be deprecated by December 5, 2024.
> update artifact actions to v4

- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
- zcutil/clean-help-dev.sh
Please don't merge this PR until all workflows in CI complete successfully. If everything goes well, the CD workflow with the Windows build should also succeed, as they are currently the same. I will leave an additional comment when it is ready for merging.
> [CI/CD] fix Windows build

- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
we should be fine with runner defaults for CI ...
> [ci/cd] save time on removal and upgrade packages
