KomodoPlatform/komodo

- src/assetchains
If you have a load of assets running and you want to quickly view which are being mined or which are eating up CPU with `htop` or `ps` it's currently pretty awakward because the pubkey pushes the params out of view.
This PR puts `-ac_name` and `-gen` first so you can quickly see from terminal output which asset chains are which and which one's are being mined.
> Reorder asset chain params for better readability

- src/chainparams.cpp
Seeds now include two hosts - static IP list and crawled active nodes using Komodo-seeder (litecoin-seeder).
Supersedes previous commits.
> DNS seeds, final commit

- .github/workflows/komodod_ci.yml
- src/bitcoind.cpp
- src/checkpoints.cpp
- src/httpserver.cpp
- src/init.cpp
- src/miner.cpp
- src/rpc/net.cpp
- src/script/sign.cpp
- src/utilstrencodings.cpp
- src/utilstrencodings.h
- src/wallet/wallet.cpp
This PR should fix daemon hang / deadlock with wallet filter enabled, also it have some fixes / patches from various upstreams (BTC, ZEC):
- code refactoring: move komodo internal structures update from wait to shutdown loop into separate thread, which seemed more logic. wait for shutdown loop almost restored to it's original state from ZEC.
- miner: remove komodo_longestchain call from miner internal loop, we defenitely don't want to iterate all connected nodes stats on each miner nOnce iteration.
- wallet filter: fully remove old blackjok3r's wallet filter code.
- wallet filter: new wallet filter implementation, key difference - now if enabled it allows txes not only from notary address and addresses listed in `-whitelistaddress`, but also from all addresses belongs to a walelt. in …
> fix hang / deadlock with wallet filter enabled and other patches

- .github/workflows/komodod_ci.yml
- doc/release-notes.md
- qa/pytest_komodo/basic/test_rawtransactions.py
- src/Makefile.test.include
- src/main.cpp
- src/pubkey.h
- src/script/script.cpp
- src/script/script.h
- src/script/standard.cpp
- src/script/standard.h
- src/test-komodo/test_eval_notarisation.cpp
- src/test/multisig_tests.cpp
- src/test/script_standard_tests.cpp
- src/wallet/rpcdump.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet_ismine.cpp
>  rm template matching and pseudo opcodes

- src/Makefile.ktest.include
- src/test-komodo/test_coinimport.cpp
- src/test-komodo/test_script_standard_tests.cpp
- added unit test for standart scripts (included one special test for non-minimal PUSHDATA forms in P2PK/P2PKH)
- temp disable non-working coin import tests (with this we can enable `komodo-test` in CI)
> Patch unit test standart scripts

- .github/workflows/komodod_cd.yml
Komodod CD workflow for GHA 
building and pushing multiOS release (Ubuntu, OSX, Windows) for pushes to branches beta, dev, research
example of autogenerated release by this flow:
https://github.com/tonymorony/komodo/releases/tag/cd_release_90f7b49_dev
> komodod test builds CD pipeline

- .github/workflows/komodod_cd.yml
- Dockerfile.release
Images will be published by GHA CD into https://hub.docker.com/repository/docker/komodoofficial/komodo repo with the same tag as GH CD release.
Image is just Ubuntu 18.04 (used it as an current most used LTE) with komodod and komodo-cli in /komodo folder (readme will be added to docker repo)
Example of docker images pushed by CD into my repo: https://hub.docker.com/repository/docker/tonymorony/komodod-test
Example of GHA run: https://github.com/tonymorony/komodo/runs/519052624
Example of image usage: https://github.com/tonymorony/komodo_docker_tests/blob/master/Dockerfile.blockchain#L1
> komodod docker image publishing in CD

- src/txmempool.cpp
In CreateNewBlock of miner https://github.com/KomodoPlatform/komodo/blob/master/src/miner.cpp#L331
we have a condition that prevents miners to include certain txes in
block if tx violates komodo_validate_interest check. so, if such txes
will exist in mempool and in some reason they was not miner earlier, if
they have nExpiryHeight = 0 - they NEVER will be included in block by miners.
Also, code in CTxMemPool::removeExpired that should remove such txes
from mempool didn't do it due to mistake. As a result these txes
stucks in mempool. No one can mine it, bcz no one can include it in block,
and no one get success to remove it from mempool.
Look on old code:
```
(ASSETCHAINS_SYMBOL[0] == 0
&& tipindex != 0 && komodo_validate_interest(...) ) < 0
```
But should be:
```
(ASSETCHAINS_SYMBOL[0] …
```
> proper removing of txes that violates interest validation from mempool

- qa/pytest_komodo/cc_modules/test_channels.py
Mihailo: `changed vout order so it is comparing marker value instead of vout to destination value.`
> fix chanelsCC test vouts

- qa/pytest_komodo/cc_modules/test_channels.py
fix broken secret reveal test
add rpc response validation
channelsrefund check no longer depends on the vout number
prevents test failure on different branches due to ChannelsCC changes
> ChannelsCC test refactor

- qa/pytest_komodo/cc_modules/util.py
In some cases CCs throwing exception such as:
`{'error': {'code': -3, 'message': 'Amount out of range'}`
And in some cases errors responses forming manually, e.g.:
`{ "result" : "error", "error" : "something" }`
lets handle both options (thanks to @dimxy for advise)
> cc errors better handling

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
- qa/pytest_komodo/cc_modules/test_token.py
After latest changes, on negative amounts in rpc calls, JsonRPC error is returned (`Amount out of range`) instead of result json. Fixed error handling/assertion for TokenCC tests.
HeirCC test will still fail, due to actual error in `heirinfo()` calls:
```
'type': 'tokens', 'lifetime': '0', 'available': '0',
```
^^ if heir contract was created with tokens, values above will always return 0 atm.
As far as I'm aware it's known problem being worked on.
Please notify me if an GitHub issue should be made.
> CC_Tokens test - fix error handling

- src/cryptoconditions/src/anon.c
- src/cryptoconditions/src/cryptoconditions.c
- src/cryptoconditions/src/ed25519.c
- src/cryptoconditions/src/eval.c
- src/cryptoconditions/src/include/secp256k1/src/ecmult_const.h
- src/cryptoconditions/src/internal.h
- src/cryptoconditions/src/prefix.c
- src/cryptoconditions/src/preimage.c
- src/cryptoconditions/src/secp256k1.c
- src/cryptoconditions/src/threshold.c
- src/cryptoconditions/src/utils.c
@Alrighttt @ca333 
To give some context, generating the fingerprint is an operation that should not fail. Previously, the `CCType.fingerprint` method was returning a (uint8_t*). This is ambiguous because it's not clear if it may ever return NULL. The fix, is to have it return `void`, and pass the pre-allocated buffer as an extra parameter. This way it gives no room for suspicion that it may fail.
> Cc fingerprint - disable NULL return values when generating fingerprint 

- src/ac/wlc
- src/assetchains.json
- src/assetchains.old
- src/fiat/wlc
WLC is no longer notarised (was replaced by WLC21)
VRSC might also be candidate for removal, as it is no longer launched as an assetchain
> remove WLC

- src/assetchains.old
Assuming this script is primarily for NN main server use - HUSH3 is launched on the 3rd party server.
Would it be worth creating `third_party` and `third_party.json` here for use on the second server, or would that be better placed in the dPoW repo?
> Remove HUSH3

- src/assetchains.json
- src/assetchains.old
MESH chain would like to activate CC modules at block height 320000. This will be a hardforking change for MESH. The date is set approximately well after the Komodo Season 4 Notary activation.
[cc: @satindergrewal]
> MESH - CC Activation at height 320000

- src/Makefile.am
- src/Makefile.ktest.include
- src/addrman.cpp
- src/addrman.h
- src/crypto/common.h
- src/fs.cpp
- src/fs.h
- src/init.cpp
- src/net.cpp
- src/net.h
- src/netbase.cpp
- src/netbase.h
- src/rpc/net.cpp
- src/test-komodo/test_addrman.cpp
- src/test-komodo/test_netbase_tests.cpp
- src/test/netbase_tests.cpp
- src/torcontrol.cpp
- src/util/asmap.cpp
- src/util/asmap.h
This is my try to port of https://github.com/bitcoin/bitcoin/pull/16702 PR in Komodo source base.
**Key points:**
- https://github.com/bitcoin/bitcoin/pull/16702
- [ASN-based bucketing of the network nodes](https://github.com/bitcoin/bitcoin/issues/16599)
- [Latest Bitcoin Core Code Release Protects Against Nation-State Attacks](https://www.coindesk.com/latest-bitcoin-core-code-release-protects-against-nation-state-attacks)
Tool for generation `ip_asn.map` file:
-  https://github.com/sipa/asmap
Small instruction of how to use:
1. Generate `ip_asn.map` with tool above, or use the attached one:
[ip_asn.tar.gz](https://github.com/KomodoPlatform/komodo/files/4743077/ip_asn.tar.gz)
2. Place it in `.komodo` folder.
3. Start the daemon with `-asmap` option:
```
-asmap=<file>
Specify asn mapping …
```
> p2p: supplying and using asmap to improve IP bucketing in addrman

- src/miner.cpp
two reasons for doing this call inside critical section:
on many cc txns sent '-25 Missing Inputs' error occurs 
chainActive.Tip might change during the call
> Added enter/leave critical section around TestBlockValidity call in BitcoinMiner()

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
- configure.ac
- src/Makefile.am
- src/cryptoconditions/configure.ac
- src/cryptoconditions/src/include/secp256k1/configure.ac
- src/secp256k1/configure.ac
- zcutil/build-mac-dtest.sh
- zcutil/build-mac.sh
- `.yml` files attempted `apt-get remove` of various PHP versions, which all fail. Removed PHP packages from apt-get remove.
- mac builds failed due to check in the gmp lib, removed check.
- dirent.h uses __unused. Added -Wno-error:attributes to CXXFLAGS on mac
- mac C headers use c++ style comments. Removed forcing compiler to c89 standard.
Outstanding questions:
- What is the purpose of the de-installation of PHP? Are such removals required?
- What is a good test of libgmp that can be used on all platforms supported?
- What version of the C compiler should we support? 2011? 2017?
> Fixes for GitHub CI (MacOS mainly)

- src/wallet/rpcwallet.cpp
Note that in another PR, in cleanwallettransactions, I may add a call to backupwallet prior to deleting txes + a warning to explain. I don't know if it is better to add it inside cleanwallettransactions or add the call to backupwallet in each script (Labs, webworker01, ...) that is using cleanwallettransactions. To be safe, I'd prefer to add it into komodo's code of cleanwallettransactions.
> cleanwallettransactions: fix typos in JSON output

- src/komodo-tx.cpp
- src/komodo_utils.h
- src/script/standard.cpp
- src/wallet-utility.cpp
disable vSolutions size > 1 after June2021 HF as it might break addressindex (this was mistakenly pulled from verus code)
> ExtractDestination is disabled to have vsolutions size > 1

- src/komodo_bitcoind.h
this also will fix build on OS with default compiler - gcc 11.1.x
such as archlinux 5.2.16 and others.
(c) https://github.com/DeckerSU/KomodoOcean/commit/f4ed74c66beb6abf329c7e9fb3af3b3fb6199c8f
> fix cJSON* pointer compare with int

- zcutil/VerusCoin.xml
- zcutil/fetch-params.bat
- zcutil/fetch-params.sh
as zcash seems delete sprout related files (sprout-proving.key,
sprout-verifying.key) from their hosting (z.cash), we need
to switch on our one hosting to download these files, as komodo
still needed them.
> change zcash params files location to self-hosted

- src/komodo_defs.h
- src/komodo_globals.h
- 3rd-party pubkeys for S5 added
- S5 starts from `nS5Timestamp = 1627466969` (TOKEL `block #1` timestamp)
> add S5 3rd-party notaries pubkeys for TOKEL

- src/Makefile.am
without these changes you will catch several linkage errors, like:
```
/usr/bin/ld: libbitcoin_server.a(libbitcoin_server_a-mini-gmp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
libbitcoin_server.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```
More detailed information:
https://github.com/DeckerSU/komodo/commit/d99e7d205ba42ff1a2c4138a2910e56b91eec096
> fix build with gcc 5.4.0

- src/komodo.cpp
- src/komodo_structs.cpp
- src/komodo_structs.h
Fix `[COIN] verifynotarization error unexpected dest.(...)` error.
@jmjatlanta @dimxy @ca333 plz, review it.
**p.s.** As we forgot to init `dest` field in two places, i made it part of ctor's to prevent such mistakes in future.
> fix init of event_notarized dest field

- src/komodo_structs.cpp
- src/komodo_structs.h
The `dest` member of the `event_notarized` class could end up without a null terminator in some instances. This fix eliminates the possibility.
> Assure last char of event_notarized::dest is 0

- depends/packages/bdb.mk
- depends/packages/boost.mk
- depends/packages/zeromq.mk
More details here: https://github.com/bitcoin/bitcoin/pull/22840
Affected libraries in our case:
- bdb
- boost
- zeromq
> build: fix unoptimized libraries in depends

- src/init.cpp
The `pnotarisations` object was not `delete`d during daemon shutdown. While not a good thing, it was harmless in the past, due to the program exiting soon thereafter. However, this has recently caused problems on MacOS, so needs to be fixed.
> Clean up memory on shutdown

- README.md
Ubuntu 18.04 is EOL in April. Current deps in README.md fail on `python python-zmq` in 20.04.5. Changing this to `python3 python3-zmq` works.
> update deps for 20.04

- src/init.cpp
- src/komodo.cpp
- src/komodo.h
- src/komodo_bitcoind.cpp
- src/komodo_bitcoind.h
- src/komodo_events.cpp
- src/komodo_events.h
- src/komodo_gateway.cpp
- src/komodo_gateway.h
- src/komodo_utils.cpp
- src/test-komodo/test_events.cpp
Use a new komodoevents file name instead of komodostate to avoid removing the corrupted file on startup
Fix loading last nota from komodoevents (also logging added)
> Use a new name for komodostate file; fix loading last nota

- depends/packages/libevent.mk
port of https://github.com/DeckerSU/KomodoOcean/commit/a9e08d2c2e775fef905080e8bfa9f7786b4d9d8e to komodo codebase.
initially it was related to PR https://github.com/KomodoPlatform/komodo/pull/568 opened by @TheComputerGenie , but without -D_WIN32_WINNT=0x0601 fix, introduced in https://github.com/bitcoin/bitcoin/commit/eb6b73540d1ee7ff5a6874dd0e35f9b30b68e3b8 it will have issues with binding the RPC server to a ipv6 address on Windows , described here https://github.com/bitcoin/bitcoin/pull/19375 .
> bump libevent to 2.1.12

- src/Makefile.am
- src/Makefile.ktest.include
- src/test-komodo/komodo-test-res.rc
- src/test-komodo/main.cpp
- src/test-komodo/test_block.cpp
- src/test-komodo/test_coins.cpp
- src/test-komodo/test_eval_notarisation.cpp
- src/test-komodo/test_parse_notarisation.cpp
- src/test-komodo/testutils.cpp
- src/wallet-utility-res.rc
fix komodo-test.exe and wallet-utility.exe builds,
fix missed inits and cleanups, skip tests unsupported on windows for all tests to pass in komodo-test
> fix komodo-test and wallet-utility for windows

- src/secp256k1/src/ecmult_impl.h
`secp256k1_ecmult_multi_var_simple` was introduced by `jl777` in `ENABLE_MODULE_MUSIG` commit https://github.com/KomodoPlatform/komodo/commit/c127a8f0b5bfd89e76364e6432c8a70b5eb3a203 . originally these changes was introduced by `jonasnick` here: https://github.com/BlockstreamResearch/secp256k1-zkp/pull/35/files#diff-dc206b3f5f973b97a0f5c1b12d705d0e58a1cb8c9684e481e7a34fc05e4716aa . eventually, the changes made in this commit were applied to Bitcoin Core via https://github.com/bitcoin-core/secp256k1/pull/580 , and during the conversation https://github.com/bitcoin-core/secp256k1/pull/580/files#r255427342 initialization of `tmpj` was added.
this fix helps to fix this error during build:
```
In file included from src/secp256k1.c:14:
In function ‘secp256k1_ecmult’,
inlined from …
```
> secp256k1: fix possible read from uninitialized memory (tmpj)

- src/komodo_hardfork.cpp
- src/komodo_hardfork.h
Harvested via https://github.com/KomodoPlatform/NotaryNodes/blob/master/season7/elected_nn_social.json
Hardfork block estimate calculated with https://github.com/KomodoPlatform/NotaryNodes/blob/master/utils/generate_nn_social.py#L208-L227
```
Enter the target hardfork timestamp: 1688132253
Enter the current block height: 3423973
Seconds until HF: 3781131
Expected blocks until HF: 63018
Checkpoint block: 3360955
Checkpoint blocktime: 1680424784
Time since checkpoint: 3926338
Seconds per block average: 62
Estimated blocks until HF: 60985
Estimated HF block: 3484958
```
> Add S7 pubkeys and HF estimate

- src/deprecation.h
- src/komodo_hardfork.cpp
- src/komodo_hardfork.h
- src/komodo_interest.cpp
- src/test-komodo/test_kmd_feat.cpp
Don't merge until `nS7HardforkHeight` will be determined. Then we will need an additional commit to change `7113400` to `nS7HardforkHeight` in sources.
Changes are needed in the following places:
- https://github.com/KomodoPlatform/komodo/commit/b5b7f76af25110862b2de43325eb054c8223a9ed#diff-ef1222ae038a82df4aaa7d006ba503454ad1758fcd70265adef8180ac06e790dR34
- https://github.com/KomodoPlatform/komodo/commit/b8b0f806f7e5ebeb2c676cce9ccc8855a1ac4fa1#diff-0fcc50c6d3e39073b011940ec4972e0b6bbc40e6a65db1202f2804197749cd59R265
> reduce AUR 5% -> 0.01% after nS7HardforkHeight

- depends/packages/libcurl.mk
- https://curl.se/docs/CVE-2023-38545.html
- https://curl.se/docs/CVE-2023-38546.html
> bump libcurl to 8.4.0

- .github/workflows/komodo_mac_ci.yml
- contrib/devtools/update-rust-hashes.sh
- depends/packages/librustzcash.mk
- depends/packages/rust.mk
- zcutil/build-mac-dtest.sh
- zcutil/build-mac.sh
This pull request updates Rust to version 1.69.0. However, we still need to rework the Rust integration, build the crates, and address other related issues. Additionally, this update is expected to resolve the known "not mach-o or llvm bitcode file" issue on MacOS native builds, as described here: https://github.com/KomodoPlatform/komodo/pull/594#issuecomment-1770050716. Please refrain from merging this pull request until all tests, including a sync from scratch and sapling crypto, have been completed.
Furthermore, we have the opportunity to address the warnings that arise during the build of Rust crates.
> update rust to 1.69.0

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
as the bootstrap_url (https://sirseven.me/share/bootstrap.tar.gz) is no more accessible we will temp disable these jobs, until revise/rethink needed steps (mean, CC is kind of EOL, do we still need these tests here?) and re-create chains, if needed.
> temp disable CC and basic RPC jobs in workflows

- src/Makefile.ktest.include
- src/komodo.cpp
- src/komodo_utils.cpp
- src/test-komodo/test_block.cpp
- src/test-komodo/test_kmd_feat.cpp
- src/test-komodo/test_legacy_events.cpp
- src/test-komodo/test_parse_args.cpp
It has been discovered that in certain environments, such as when building a daemon on MacOS using the native `clang` instead of the default `gcc` provided in the repository, the daemon binary had a bug with the `p2p/rpc port` and `magic` (only for ACs, KMD itself was not affected). This bug was caused by incorrect extrabuf filling. Further investigation revealed that this behavior was due to not properly clearing some internal variables and a dangling pointer issue. This pull request fixes this erroneous behavior and also resolves compatibility issues between legacy events tests and the `test_block` test. The `LegacyEventsTests` were not functioning correctly (showing errors) when run immediately after the `test_block` tests due to changes in the values of certain global variables and …
> fix komodo_args, add ParseArgumentsTests, fix LegacyEvents test

- depends/packages/boost.mk
- depends/patches/boost/ignore_wnonnull_gcc_11.patch
this patch fixes errors like:
```
include/boost/concept/detail/general.hpp:39:47: warning: 'this' pointer null [-Wnonnull]
39 |     static void failed() { ((Model*)0)->~Model(); }
```
during build with gcc 11.x, more details can be found here:
- https://github.com/boostorg/concept_check/issues/27
- https://github.com/boostorg/concept_check/pull/28
> depends: patch boost to ignore -Wnonnull new gcc 11 warnings

- src/wallet/wallet.cpp
- src/wallet/wallet.h
Passing CWalletDB to OrderedTxItems() drastically speeds up importprivkey (and prevents py tests from failure on timed out importprivkey)
> Pass CWalletDB to OrderedTxItems() as optional param

- qa/pytest_komodo/cc_modules/test_channels.py
- qa/pytest_komodo/lib/pytest_util.py
- qa/pytest_komodo/lib/util.py
I'd like to propose a few fixes to python tests from my recent experience:
* check_synced py function may never return true. I propose a more reliable algo which simply checks that all nodes have same blocks number (More info: check_synced uses getinfo()['synced'] flag which relies on KOMODO_LONGESTCHAIN variable which sometimes may not be equal to the chain tip - it depends on which node started syncing)
* a getinfo call is used to check if komodod is started, it may return empty response -  added handling for that
* importprivkey and even the next validateaddress call in py may time out in tests due to long ScanForWalletTransactions() run - added a wait loop for that
* in check_if_mined added assert(txid) so it would fail the test if a tx creation failed
* in test_channels.py test that …
> Improve py tests err handling

- src/cryptoconditions/Makefile.am
This should resolve the build issue on `Xenial (Ubuntu 16.04)`. Officially, we do not support it as it has reached its End of Life (EOL). However, since building under Xenial is still possible, it might be a good idea to fix it. Moreover, binaries built under Xenial should also function on higher versions of Ubuntu / Linux distributions with a higher LIBC version.
Without -fPIC for libcryptoconditions_core.a build will end with error below on Xenial:
```
/usr/bin/ld: cryptoconditions/libcryptoconditions_core.a(libcryptoconditions_core_a-cryptoconditions.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
cryptoconditions/libcryptoconditions_core.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```
> build: fix build on xenial (16.04)

- .github/workflows/komodo_mac_ci.yml
- depends/packages/boost.mk
- depends/patches/boost/range_enums_clang_16.patch
error: integer value -1 is outside the valid range of values [0, 3] for this enumeration type
- https://trac.macports.org/ticket/69103
- https://github.com/boostorg/numeric_conversion/commit/50a1eae942effb0a9b90724323ef8f2a67e7984a
**p.s.** Don't merge until tests are completed.
> mac build: fix boost 1.72 build error with clang 16

- .github/workflows/komodod_cd.yml
Once merged to master, this will allow an "on demand" workflow trigger button which will build the linux binary and upload it to dockerhub for any future branch, which can then be used for testing in a dockerised environment (e.g. via https://github.com/smk762/qa_postman_tests).
When the workflow is manually triggered from the workflow dispatch button, it will not process  the build steps for MacOS/Windows, and skip the release binary upload steps.
Example from my fork:
> Allow on demand publishing to dockerhub

- .github/workflows/komodod_cd.yml
The latest macOS build workflow in the CD seems to have failed — here’s the link: [https://github.com/KomodoPlatform/komodo/actions/runs/10460396907](https://github.com/KomodoPlatform/komodo/actions/runs/10460396907). This PR is an attempt to fix it.
> fix osx-build komodod CD workflow

- src/komodo_bitcoind.cpp
The KIP0003 consensus rule was added in the `dev` branch as "logging only", i.e. as disabled. However, in the `patch-s8-prepare-hf-test` branch, which we used for testing on hfnet, it's already enabled
(as seen in [this commit](https://github.com/KomodoPlatform/komodo/commit/783fc1f83144d05a1dc6103d5dae4ef677bf241f)). For the release, we should enable this rule and make the logging optional using the hfnet category.
> enable KIP0003 consensus rule

- .github/workflows/komodo_linux_ci.yml
- .github/workflows/komodo_mac_ci.yml
- .github/workflows/komodo_win_ci.yml
- .github/workflows/komodod_cd.yml
- src/chainparams.cpp
- src/wallet-utility.cpp
There was an error with relaying and propagating transactions on the `new GLEEC` chain. Since the `old GLEEC` chain was protected with checkpoints and the new chain shares the same ticker, the node assumed that Initial Block Download (IBD) hadn’t finished and therefore didn’t accept `tx` p2p messages. The system wasn’t designed to handle two different chains with the same name. This PR resolves the issue. In the future, I recommend deprecating the old GLEEC chain and avoiding such conflicts to prevent similar issues.
> fix old and new gleec checkpoints

- src/cryptoconditions/src/include/ed25519/src/verify.c
- src/cryptoconditions/src/include/ed25519/test.c
- src/cryptoconditions/test-requirements.txt
cc: fix ed25519 signatures malleability
- https://github.com/KomodoPlatform/komodo/issues/630
- https://soatok.blog/2024/08/14/security-issues-in-matrixs-olm-library/#vuln-ed25519
Actually, the current CC code doesn’t use Ed25519 signatures, so `CVE-2024-45193` has no impact on Komodo (KMD) or any existing assetchains. However, since CC could potentially use these types of signatures in the future (e.g., for newly developed CCs), we’ve added a `0 <= s < L` check to prevent signature malleability.
Tests: https://github.com/KomodoPlatform/komodo/commit/afcb471fbf5bb7a9ef0c5435cbee06c4738404bd
Before changes:
```
testing signature malleability
Signature:
0f 03 c0 e6 2c 38 ed 29
48 26 93 38 07 4a 25 f7
75 e1 db ce 6f 7d da 02
c6 c3 fd da 4c 7d d4 6b
bb f9 d4 06 5b fe 1f ff
34 1f 93 6d 7e ab …
```
> cc: fix ed25519 signatures malleability

- depends/packages/libsodium.mk
As of August 30, 2024, `git.savannah.gnu.org` returned a 502 error when trying to download `config.guess` and `config.sub`. For example, attempting to download [this link](https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD) returned a 502 error. As a result, all scripts, workflows, etc., that relied on getting fresh versions of `config.{sub,guess}` from `git.savannah.gnu.org` are failing. To prevent this, we disabled updating to the fresh versions of these scripts.
- https://github.com/DeckerSU/KomodoOcean/commit/4a298288c2f66c8fc1abd27aa78de52c1d7c5a70
- https://github.com/KomodoPlatform/komodo/pull/633
> libsodium: don't update config.sub, congig.guess from git.savannah.gnu.org

- src/chainparams.cpp
- src/komodo_utils.cpp
This update should fix the notarization issue with the old GLEEC chain. After applying the fix, the output of the `getinfo` RPC call should look something like this:
```bash
komodo-cli -ac_name=GLEEC -datadir=/home/builder/.komodo/GLEEC_OLD getinfo | jq .
```
```json
{
"version": 90000,
"protocolversion": 170013,
"KMDversion": "0.9.0",
"synced": true,
"notarized": 974444,
"prevMoMheight": 974444,
"notarizedhash": "0958f1dd625d89d5749b698cbf7e57eb294dd1916d828d60fbf9de9dfd9053e4",
"notarizedtxid": "7fdc3a5452baef619452408cc31fac86de468755380914d7f172dc78b7702ac8",
"notarizedtxid_height": "mempool",
"KMDnotarized_height": 0,
"notarized_confirms": 0,
"walletversion": 60000,
"balance": 0,
"blocks": 974458,
"longestchain": 974458,
"tiptime": 1728914950,
"difficulty": 1,
"keypoololdest": …
```
> GLEEC_OLD: exception to fix following the notarizations

- src/wallet/wallet.cpp
As is well known, Iguana uses P2PKH UTXOs for splitting and converts them into 10,000 zat P2PK UTXOs for notarizing. However, it cannot split from P2PK UTXOs. When you run `komodod` with the `-pubkey` argument, specifying your notary pubkey, any transaction created inside the daemon will send change (if any) as a P2PK output, i.e., to the `<pubkey> OP_CHECKSIG` script. As a result, Iguana cannot split such UTXOs. This change modifies that behavior, making the change a standard P2PKH output if a pubkey is specified.
- https://github.com/DeckerSU/KomodoOcean/pull/81
> use p2pkh vout instead of p2pk for change when -pubkey specified

- src/bitcoind.cpp
- src/init.cpp
- src/main.cpp
- src/main.h
- src/util.cpp
- src/util.h
No `komodo.conf` file for KMD is OK
> allow to start without komodo.conf for KMD

- src/Makefile.am
This PR fixes linkage error below on Xenial:
```
/usr/bin/ld: libcc.a(libcc_a-cclib.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
libcc.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:2305: recipe for target 'komodod' failed
make[2]: *** [komodod] Error 1
```
> fix linkage on Xenial (16.04)

- Dockerfile.release
Current output sent to dockerhub is faulty, as the GHA build environment [`runs-on: ubuntu-22.04`](https://github.com/KomodoPlatform/komodo/blob/master/.github/workflows/komodod_cd.yml#L19), but the docker base image was set to run `FROM ubuntu:20.04`.
The result was the following errors on launching the images uploaded to dockerhub 
```
komodo-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by komodo-cli)
komodo-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by komodo-cli)
komodo-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by komodo-cli)
````
By aligning the GHA build env and dockerfile base image, these errors will be avoided.
> use ubuntu22 image
